(()=>{'use strict';
 const $=s=>document.querySelector(s),audio=$('#voice'),canvas=$('#plot'),ctx=canvas.getContext('2d');
 const colors={ink:'#1c303c',muted:'#738892',grid:'#e6ebed',wave:'#a5b1b6',teal:'#087e85',orange:'#be641a',red:'#cb5964'};
 const slides=[
 {nav:'01 采样',label:'01 / SAMPLING',title:'采样，选择时间位置',lead:'波形上有了点，就已经是数字信号了吗？',concept:'时间离散，幅值尚未量化',formula:'x[N] = xₐ(NT)<br><small>T = 1 / fₛ</small>',points:['<strong>采样间隔 T</strong>：相邻两次取值之间的时间。','<strong>整数序号 N</strong>：把每个采样时刻编号。','<strong>取值 x[N]</strong>：仍可取连续幅值集合中的值。'],takeaway:'采样只回答“什么时候取值”。',legend:[['连续时间模型','wave'],['理想采样值','teal']]},
 {nav:'02 量化',label:'02 / QUANTIZATION',title:'量化，选择幅值电平',lead:'时刻不变，让样本落在规定的电平上。',concept:'同一个时刻，数值被近似',formula:'L = 2ᵇ　　Δ = 2 / L',points:['<strong>量化范围 [−1, 1]</strong>：均分为 L 个区间。','<strong>区间中心</strong>：代表落入该区间的采样值。','<strong>未过载时</strong>：|xq[N] − x[N]| ≤ Δ / 2。'],takeaway:'量化决定电平，编码给电平编号。',legend:[['采样值','teal'],['量化值','orange'],['量化误差','red']]},
 {nav:'03 分类',label:'03 / CLASSIFICATION',title:'两个属性，分别判断',lead:'横轴看时间，纵轴看幅值。',concept:'“离散”要说清楚是哪一维',formula:'时间 × 幅值',points:['<strong>时间</strong>：处处有定义，还是只在离散时刻取值？','<strong>幅值</strong>：可连续取值，还是只能选规定电平？','<strong>数字信号</strong>：时间、幅值都离散。'],takeaway:'波形有跳变，不代表时间离散。',legend:[['当前讲解的信号','teal'],['其余类型','wave']]},
 {nav:'04 系统',label:'04 / SYSTEM',title:'系统，把输入变成输出',lead:'用一条运算规则，描述一个简单系统。',concept:'同一序号，幅度乘以 0.5',formula:'y[N] = 0.5 x[N]',points:['<strong>输入</strong>：一组序列 x[N]。','<strong>运算</strong>：每个样本都乘以 0.5。','<strong>输出</strong>：幅度减半，时间位置不变。'],takeaway:'有限字长实现，还要考虑输出如何表示。',legend:[['输入 x[N]','teal'],['输出 y[N]','orange']]},
 {nav:'05 动手试',label:'05 / EXPERIMENT',title:'只改一个参数，看哪里变了',lead:'先预测，再改参数，然后用图来解释。',concept:'把时间与幅值的影响分开',formula:'fₛ 管时间　　b 管幅值',points:['<strong>第一轮</strong>：固定 3 位，采样率从 16 改为 32。','<strong>第二轮</strong>：固定采样率，量化从 3 位改为 8 位。','<strong>检查</strong>：横向间距、幅值台阶，哪一个变了？'],takeaway:'加密采样点与细化幅值电平，是两件事。',legend:[['采样值','teal'],['量化值','orange'],['量化误差','red']]}
 ];
 let page=0,raf=0,loadingToken=0,lastCue=-1;
 const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
 const config=(fs,bits)=>DATA.configs.find(d=>d.fs===fs&&d.bits===bits);
 const lesson=()=>LESSONS[page];
 const time=()=>page<4?audio.currentTime:0;
 const fmt=n=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
 function label(x,y,t,size=16,color=colors.muted,align='left'){ctx.fillStyle=color;ctx.font=`${size}px "Microsoft YaHei", sans-serif`;ctx.textAlign=align;ctx.fillText(t,x,y);}
 function line(x1,y1,x2,y2,color,width=1){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
 function dot(x,y,color,r=5,fill=true){ctx.beginPath();ctx.arc(x,y,r,0,2*Math.PI);ctx.strokeStyle=color;ctx.fillStyle='#fff';ctx.lineWidth=2.3;fill?ctx.fillStyle=color:null;ctx.fill();ctx.stroke();}
 function square(x,y,color,r=4){ctx.fillStyle=color;ctx.fillRect(x-r,y-r,2*r,2*r);}
 function grid(box={x:58,y:28,w:812,h:300},labels=true){const px=t=>box.x+t*box.w,py=v=>box.y+box.h*(1-(v+1)/2);[-1,-.5,0,.5,1].forEach(v=>{line(box.x,py(v),box.x+box.w,py(v),v===0?'#c9d4d8':colors.grid);if(labels)label(box.x-13,py(v)+5,String(v),14,colors.muted,'right');});[0,.25,.5,.75,1].forEach(t=>{line(px(t),box.y,px(t),box.y+box.h,colors.grid);if(labels)label(px(t),box.y+box.h+28,String(t),14,colors.muted,'center');});if(labels){label(box.x,box.y-10,'归一化幅值',14);label(box.x+box.w,box.y+box.h+54,'时间 t / s',14,colors.muted,'right');}return{px,py,box};}
 function wave(g,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.beginPath();DATA.t.forEach((t,i)=>i?ctx.lineTo(g.px(t),g.py(DATA.wave[i])):ctx.moveTo(g.px(t),g.py(DATA.wave[i])));ctx.strokeStyle=colors.wave;ctx.lineWidth=2;ctx.stroke();ctx.restore();}
 function samples(g,c,count=c.t.length){c.t.forEach((t,i)=>{if(i>=count)return;line(g.px(t),g.py(0),g.px(t),g.py(c.x[i]),'#a3cdce',1.4);dot(g.px(t),g.py(c.x[i]),colors.teal,4.5,false);});}
 function quant(g,c,morph=1,errors=true){if(c.bits===3)c.levels.forEach(v=>{ctx.setLineDash([4,5]);line(g.box.x,g.py(v),g.box.x+g.box.w,g.py(v),'#e3c6a7');ctx.setLineDash([]);});c.t.forEach((t,i)=>{const x=g.px(t),a=g.py(c.x[i]),b=g.py(c.x[i]+(c.q[i]-c.x[i])*morph);if(errors)line(x,a,x,b,colors.red,2.8);dot(x,a,colors.teal,4.3,false);square(x,b,colors.orange,4);});}
 function drawSampling(t){const fs=t>=29.06?32:16,c=config(fs,3),g=grid();wave(g);const count=t<9.2?0:t<18.22?Math.ceil(clamp((t-9.2)/9.02)*c.t.length):c.t.length;samples(g,c,count);$('#scene-meta').textContent=`fₛ = ${fs} Hz · T = ${(1/fs).toFixed(5)} s`;$('#visual-caption').textContent=t<9.2?'连续时间模型：任意时刻都有定义。':`1 秒观察窗内 ${c.t.length} 个采样点（不重复计入 t = 1 的端点）。`;}
 function drawQuant(t,lab=false){const bits=lab?Number($('#bits').value):(t>=32.45?8:3),fs=lab?Number($('#fs').value):16,c=config(fs,bits),g=grid();wave(g,.4);const morph=lab?1:clamp((t-8.03)/6);quant(g,c,morph,lab||t>=16.18);$('#scene-meta').textContent=`${bits} 位 · ${2**bits} 个电平 · Δ = ${c.delta}`;if(!lab&&t>=23.95&&t<32.45){let k=4;label(g.px(c.t[k])+12,g.py(c.q[k])-17,`编码 ${c.codes[k].toString(2).padStart(3,'0')}`,18,colors.orange);}
 $('#visual-caption').textContent=lab?`最大误差 ${c.max_error.toFixed(6)}；未过载误差界 Δ/2 = ${(c.delta/2).toFixed(6)}。`:(bits===3?'3 位电平取各区间中心，本例不包含零电平。':'采样时刻保持不变；8 位的幅值台阶比 3 位更细。');}
 function classifyActive(t){return t<7.74?0:t<17.43?2:t<35.78?1:3;}
 function drawClassify(t){const active=classifyActive(t);label(244,25,'幅值连续',18,colors.ink,'center');label(672,25,'幅值离散',18,colors.ink,'center');const defs=[['时间连续','连续时间信号',0],['时间连续','有限电平的连续时间波形',1],['时间离散','理想采样序列',2],['时间离散','数字信号',3]];defs.forEach(([row,name,k])=>{const bx=k%2===0?22:459,by=k<2?49:230;ctx.fillStyle=k===active?'#edf7f6':'#f8fafb';ctx.fillRect(bx,by,414,162);label(bx+14,by+24,row+' · '+name,15,k===active?colors.teal:colors.muted);const g={box:{x:bx+25,y:by+43,w:365,h:96},px:v=>bx+25+v*365,py:v=>by+43+48-v*44};line(g.box.x,g.py(0),g.box.x+365,g.py(0),'#d3dfe2');ctx.save();ctx.globalAlpha=k===active?1:.4;if(k===0)wave(g);if(k===1){const steps=[0,.14,.37,.51,.74,.9,1];steps.slice(0,-1).forEach((st,j)=>{const v=j%2;line(g.px(st),g.py(v*.8),g.px(steps[j+1]),g.py(v*.8),colors.orange,2.3);if(j<steps.length-2)line(g.px(steps[j+1]),g.py(v*.8),g.px(steps[j+1]),g.py((1-v)*.8),colors.orange,2.3);});}if(k===2)samples(g,config(16,3));if(k===3){const c=config(16,3);c.t.forEach((v,j)=>{line(g.px(v),g.py(0),g.px(v),g.py(c.q[j]),'#d8b38c');square(g.px(v),g.py(c.q[j]),colors.orange,3.6);});}ctx.restore();});$('#scene-meta').textContent='时间与幅值，两个独立的分类属性';$('#visual-caption').textContent='亮起的图对应当前讲解；另外三类保留作对照。';}
 function drawSystem(t){const c=config(16,3),g=grid();samples(g,c);if(t>=10.36){const f=clamp((t-10.36)/5);c.t.forEach((v,i)=>{let q=c.x[i]*(1-.5*f);line(g.px(v),g.py(c.x[i]),g.px(v),g.py(q),'#e0b78f',2);square(g.px(v),g.py(q),colors.orange,4.5);});}$('#scene-meta').textContent='y[N] = 0.5 x[N]';$('#visual-caption').textContent=t<10.36?'先观察输入序列，再看运算怎样改变输出。':'同一个 N 对应同一个时刻，改变的是样本的幅度。';}
 function draw(){const scale=Math.min(devicePixelRatio||1,2);if(canvas.width!==900*scale){canvas.width=900*scale;canvas.height=410*scale;}ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,900,410);ctx.textBaseline='alphabetic';if(page===0)drawSampling(time());else if(page===1)drawQuant(time());else if(page===2)drawClassify(time());else if(page===3)drawSystem(time());else drawQuant(0,true);}
 function cueIndex(){if(page===4)return 0;const units=lesson().units,idx=units.findIndex(u=>time()<u.end);return idx<0?units.length-1:idx;}
 function update(){if(page<4){const l=lesson(),idx=time()>=l.duration?l.units.length-1:cueIndex();$('#seek').value=Math.min(time(),l.duration);$('#clock').textContent=`${fmt(time())} / ${fmt(l.duration)}`;if(idx!==lastCue){$('#transcript').textContent=l.units[idx].text;$('#cue-index').textContent=`${String(idx+1).padStart(2,'0')} / ${String(l.units.length).padStart(2,'0')}`;lastCue=idx;}$('#prev-cue').disabled=idx===0;$('#next-cue').disabled=idx===l.units.length-1;}draw();}
 function playingUI(){const playing=page<4&&!audio.paused;$('#play').innerHTML=playing?'Ⅱ<span>暂停讲解</span>':'▶<span>播放讲解</span>';$('#play').setAttribute('aria-label',playing?'暂停讲解':'播放讲解');}
 function tick(){update();if(!audio.paused&&page<4)raf=requestAnimationFrame(tick);}
 async function toggle(){if(page===4)return;if(audio.paused){if(time()>=lesson().duration-.1)audio.currentTime=0;const token=loadingToken;try{await audio.play();if(token!==loadingToken)return;$('#status').textContent='正在讲解；可随时暂停、逐句跳转或拖动进度。';}catch(e){if(token===loadingToken)$('#status').textContent='暂时无法播放音频。请确认 assets 文件夹完整；仍可拖动进度查看动画与讲解词。';}}else audio.pause();}
 function navigate(n){n=clamp(n,0,4);loadingToken++;audio.pause();cancelAnimationFrame(raf);page=n;lastCue=-1;const s=slides[n];$('#section').textContent=s.label;$('#title').textContent=s.title;$('#lead').textContent=s.lead;$('#concept').textContent=s.concept;$('#formula').innerHTML=s.formula;$('#points').innerHTML=s.points.map(x=>`<p>${x}</p>`).join('');$('#takeaway').textContent=s.takeaway;$('#legend').innerHTML=s.legend.map(([name,c])=>`<span><i style="--c:${colors[c]}"></i>${name}</span>`).join('');$('#page-number').textContent=`${String(n+1).padStart(2,'0')} / 05`;$('#prev').disabled=n===0;$('#next').disabled=n===4;$('#lab-controls').hidden=n!==4;canvas.setAttribute('aria-label',s.title+'。'+s.takeaway);
 document.querySelectorAll('#pages button').forEach((b,i)=>{if(i===n)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});
 for(const q of ['#play','#reset','#seek','#speed','#sound','#prev-cue','#next-cue'])$(q).disabled=n===4;
 if(n<4){audio.src=lesson().audio;audio.load();audio.playbackRate=Number($('#speed').value);audio.muted=!$('#sound').checked;$('#seek').max=lesson().duration;$('#seek').value=0;$('#status').textContent='点击播放开始；空格暂停，左右方向键翻页。每屏结束后停留，便于课堂讨论。';}else{audio.removeAttribute('src');audio.load();$('#clock').textContent='自由实验';$('#seek').value=0;$('#transcript').textContent='先固定量化位数，把采样率从每秒 16 次改为 32 次。再固定采样率，把 3 位改为 8 位。每次只改一个参数，观察横向间距与幅值台阶分别怎样变化。';$('#cue-index').textContent='独立操作';$('#status').textContent='这一屏没有自动讲解。先预测，再选择参数，用变化的图验证自己的判断。';}
 try{history.replaceState(null,'',`#${n+1}`);}catch(e){}playingUI();update();}
 $('#pages').innerHTML=slides.map((s,i)=>`<button type="button" data-page="${i}" aria-label="第${i+1}屏 ${s.title}">${s.nav}</button>`).join('');$('#pages').addEventListener('click',e=>{const b=e.target.closest('button');if(b)navigate(Number(b.dataset.page));});
 $('#play').addEventListener('click',toggle);$('#prev').addEventListener('click',()=>navigate(page-1));$('#next').addEventListener('click',()=>navigate(page+1));$('.brand').addEventListener('click',e=>{e.preventDefault();navigate(0);});
 $('#reset').addEventListener('click',()=>{audio.pause();audio.currentTime=0;lastCue=-1;update();});$('#seek').addEventListener('input',e=>{audio.currentTime=Number(e.target.value);update();});$('#sound').addEventListener('change',()=>{audio.muted=!$('#sound').checked;});$('#speed').addEventListener('change',()=>{audio.playbackRate=Number($('#speed').value);});
 function seekCue(delta){if(page>=4)return;const i=clamp(cueIndex()+delta,0,lesson().units.length-1);audio.currentTime=lesson().units[i].start+.015;update();}$('#prev-cue').addEventListener('click',()=>seekCue(-1));$('#next-cue').addEventListener('click',()=>seekCue(1));
 ['fs','bits'].forEach(id=>$('#'+id).addEventListener('change',draw));audio.addEventListener('play',()=>{cancelAnimationFrame(raf);playingUI();tick();});audio.addEventListener('pause',()=>{cancelAnimationFrame(raf);playingUI();update();});audio.addEventListener('seeked',update);audio.addEventListener('loadedmetadata',()=>{audio.playbackRate=Number($('#speed').value);update();});audio.addEventListener('ended',()=>{$('#status').textContent='本屏讲解结束。可以停下来讨论，或点击右箭头进入下一屏。';playingUI();update();});
 audio.addEventListener('error',()=>{if(page<4&&audio.getAttribute('src'))$('#status').textContent='音频未能载入。请把 assets 文件夹与 index.html 一起保留。';});
 document.addEventListener('keydown',e=>{if(e.target.closest('input,select,button,summary,a'))return;if(e.code==='Space'){e.preventDefault();toggle();}if(e.code==='ArrowRight'){e.preventDefault();navigate(page+1);}if(e.code==='ArrowLeft'){e.preventDefault();navigate(page-1);}});
 $('#full').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('.deck').requestFullscreen();}catch(e){$('#status').textContent='此浏览器暂不支持页面全屏，可使用浏览器的 F11 全屏。';}});document.addEventListener('fullscreenchange',()=>{$('#full').textContent=document.fullscreenElement?'退出全屏':'全屏投影';});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)audio.pause();});window.addEventListener('resize',draw);window.addEventListener('hashchange',()=>{const n=Number(location.hash.slice(1))-1;if(Number.isInteger(n)&&n>=0&&n<5&&n!==page)navigate(n);});
 // Compact read-only state for local QA; calculations use the original MATLAB dataset.
 window.lessonState=()=>({page,time:time(),cue:page<4?cueIndex():null,fs:page===4?Number($('#fs').value):(page===0&&time()>=29.06?32:16),bits:page===4?Number($('#bits').value):(page===1&&time()>=32.45?8:3)});
 const hash=Number(location.hash.slice(1));navigate(hash>=1&&hash<=5?hash-1:0);
})();
