(()=>{'use strict';
const $=s=>document.querySelector(s),a=$('#voice'),cv=$('#plot'),ctx=cv.getContext('2d'),C={ink:'#1c303c',muted:'#738892',grid:'#e5ebed',gray:'#a7b1b6',teal:'#087e85',orange:'#be641a',red:'#bf5060',blue:'#6483ad'};
let page=0,raf=0,lastCue=-1,manual=false,token=0,observed={};
const s=()=>SLIDES[page],clamp=(v,l=0,h=1)=>Math.max(l,Math.min(h,v)),tm=()=>a.getAttribute('src')?a.currentTime:0,progress=()=>clamp(tm()/(s().duration||1)),sinc=x=>Math.abs(x)<1e-12?1:Math.sin(Math.PI*x)/(Math.PI*x);
const config=(fs,kind='cos')=>SAMPLING.configs.find(c=>c.fs===fs&&c.kind===kind),reco=(fs=12,M=12)=>RECON.configs.find(c=>c.fs===fs&&c.M===M);
function cue(){let i=s().units.findIndex(u=>tm()<u.end);return i<0?s().units.length-1:i;}
function label(x,y,t,size=17,color=C.muted,align='left'){ctx.fillStyle=color;ctx.font=`${size}px "Microsoft YaHei",sans-serif`;ctx.textAlign=align;ctx.fillText(t,x,y);}
function line(x1,y1,x2,y2,color=C.grid,width=1){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function dot(x,y,color=C.teal,r=4){ctx.beginPath();ctx.arc(x,y,r,0,2*Math.PI);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.stroke();}
function arrow(x,y0,y,color=C.teal){line(x,y0,x,y,color,2);let d=y<y0?1:-1;line(x,y,x-4,y+8*d,color,2);line(x,y,x+4,y+8*d,color,2);}
function axes({xmin=0,xmax=1,ymin=-1.3,ymax=1.3,x=58,y=38,w=812,h=272,xlabel='时间 t / s',xticks,yticks=[-1,0,1]}={}){const g={xmin,xmax,ymin,ymax,x,y,w,h,px:t=>x+(t-xmin)/(xmax-xmin)*w,py:v=>y+(ymax-v)/(ymax-ymin)*h};
 (xticks||Array.from({length:5},(_,i)=>xmin+(xmax-xmin)*i/4)).forEach(t=>{line(g.px(t),y,g.px(t),y+h);label(g.px(t),y+h+25,String(Number(t.toFixed(2))),16,C.muted,'center');});yticks.forEach(v=>{line(x,g.py(v),x+w,g.py(v),v===0?'#b8c9ce':C.grid);label(x-12,g.py(v)+5,String(v),15,C.muted,'right');});label(x+w,y+h+50,xlabel,16,C.muted,'right');return g;}
function series(g,t,v,color,width=2,dash=[]){ctx.save();ctx.beginPath();ctx.rect(g.x,g.y,g.w,g.h);ctx.clip();ctx.setLineDash(dash);ctx.beginPath();let active=false;t.forEach((x,i)=>{if(!Number.isFinite(v[i])){active=false;return;}if(active)ctx.lineTo(g.px(x),g.py(v[i]));else{ctx.moveTo(g.px(x),g.py(v[i]));active=true;}});ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();ctx.restore();}
function stems(g,t,v,color=C.teal,impulse=false){t.forEach((x,i)=>{if(x<g.xmin-1e-8||x>g.xmax+1e-8)return;impulse?arrow(g.px(x),g.py(0),g.py(v[i]),color):line(g.px(x),g.py(0),g.px(x),g.py(v[i]),color,1.3);dot(g.px(x),g.py(v[i]),color,3.7);});}
function legends(items){$('#legend').replaceChildren(...items.map(([text,color])=>{const e=document.createElement('span'),i=document.createElement('i');i.style.setProperty('--c',color);e.append(i,text);return e;}));}
function caption(meta,text,items){$('#scene-meta').textContent=meta;$('#visual-caption').textContent=text;if(items)legends(items);}
function controls(ids){document.querySelectorAll('[data-control]').forEach(el=>el.hidden=!ids.includes(el.dataset.control));$('#controls').hidden=!ids.length;}
function sampling(fs,kind,alias=false,highlight=false){const c=config(fs,kind),g=axes();series(g,SAMPLING.tc,c.wave,C.gray,2.5);if(alias)series(g,SAMPLING.tc,c.alias_wave,C.orange,2.8,[8,5]);stems(g,c.t,c.x);if(highlight){let i=Math.min(c.t.length-1,Math.floor(progress()*c.t.length));dot(g.px(c.t[i]),g.py(c.x[i]),C.red,8);label(58,22,`N = ${c.n[i]}    x[N] = ${c.x[i].toFixed(3)}`,19,C.teal);}
 observed={fs,kind,fold:c.fold,sampleCount:c.n.length,aliasError:c.alias_error};caption(`f₀ = 5 Hz · fₛ = ${fs} Hz`,alias?`同样本候选的频率为 ${Math.abs(c.fold)} Hz；其相位与符号已按样本匹配。`:`包含 t=0 与 t=1 两端点，共 ${c.n.length} 个样本。`,[['原连续信号',C.gray],['采样值',C.teal],...(alias?[['同样本低频候选',C.orange]]:[])]);}
function model(){const ideal=manual?$('#model').value==='ideal':cue()>=2;$('#model').value=ideal?'ideal':'natural';$('#duty').disabled=ideal;const d=Number($('#duty').value);$('#duty-value').textContent=d.toFixed(2);const c=config(12),g=axes();series(g,SAMPLING.tc,c.wave,C.gray,2);
 if(ideal)stems(g,c.t,c.x,C.teal,true);else{ctx.save();ctx.globalAlpha=.09;ctx.fillStyle=C.teal;c.t.forEach(t=>ctx.fillRect(Math.max(g.x,g.px(t-d/24)),g.y,Math.min(g.x+g.w,g.px(t+d/24))-Math.max(g.x,g.px(t-d/24)),g.h));ctx.restore();const v=SAMPLING.tc.map((t,i)=>Math.abs(t*12-Math.round(t*12))<=d/2?c.wave[i]:NaN);series(g,SAMPLING.tc,v,C.teal,4);}
 observed={model:ideal?'ideal':'natural',duty:d,fs:12};caption(ideal?'理想冲激 · 权重示意':`矩形脉冲 · τ/T = ${d.toFixed(2)}`,ideal?'箭头的权重是 xₐ(NT)，不是冲激函数的普通高度。':`居中单位高矩形脉冲串：cₖ = d·sinc(kd)，d = τ/T = ${d.toFixed(2)}。自然采样保留脉冲内波形。`,[['原信号',C.gray],[ideal?'加权冲激':'开关通过的波形',C.teal]]);}
function triangles(){const g=axes({xmin:-24,xmax:24,ymin:0,ymax:1.4,xlabel:'频率 f / Hz',xticks:[-24,-12,0,12,24],yticks:[0,1]});const count=cue()>=2?Math.min(2,1+Math.floor((progress()-.5)*4)):0;for(let k=-count;k<=count;k++){const t=[k*12-5,k*12,k*12+5],v=[0,1,0];series(g,t,v,k===0?C.teal:C.orange,3);label(g.px(k*12),g.py(1)-12,`k = ${k}`,17,k===0?C.teal:C.orange,'center');}observed={replicas:count*2+1,fs:12,B:5};caption('带限谱轮廓示意 · B = 5 Hz',`每隔 fₛ = 12 Hz 复制；此图用三角形表示一般带限谱支撑范围，高度归一化。`,[['中央副本',C.teal],['平移副本',C.orange]]);}
function spectral(fs,lowpass=false){const g=axes({xmin:-25,xmax:25,ymin:0,ymax:1.4,h:lowpass?160:272,xlabel:'频率 f / Hz',xticks:[-24,-12,-6,0,6,12,24],yticks:[0,1]});ctx.save();ctx.globalAlpha=.09;ctx.fillStyle=C.teal;ctx.fillRect(g.px(-fs/2),g.y,g.px(fs/2)-g.px(-fs/2),g.h);ctx.restore();
 for(let k=-2;k<=2;k++)for(const sign of [-1,1]){const f=k*fs+sign*5;if(Math.abs(f)<=25)arrow(g.px(f),g.py(0),g.py(1),k===0?C.teal:C.orange);}
 for(const f of [-fs/2,fs/2]){ctx.setLineDash([5,5]);line(g.px(f),g.y,g.px(f),g.y+g.h,C.teal);ctx.setLineDash([]);}label(g.px(0),22,`中央频带 [−${fs/2}, ${fs/2}] Hz`,18,C.teal,'center');
 if(lowpass){const y=285,g2=axes({xmin:-25,xmax:25,ymin:0,ymax:1.4,y,h:65,xlabel:'频率 f / Hz',xticks:[-24,-12,0,12,24],yticks:[]});ctx.save();ctx.globalAlpha=clamp((tm()-s().units[1].start)/4);ctx.setLineDash([6,4]);line(g.px(-fs/2),g.py(1.15),g.px(fs/2),g.py(1.15),C.blue,3);ctx.setLineDash([]);label(65,260,'理想低通后：只保留 ±5 Hz，幅度比例已补偿',19,C.teal);for(const f of [-5,5])arrow(g2.px(f),g2.py(0),g2.py(1),C.teal);ctx.restore();caption('fₛ = 12 Hz · 理想恢复示意','通带增益为 T = 1/12 s，图中谱线高度作归一化显示。',[['中央 / 输出谱线',C.teal],['其他副本',C.orange],['理想低通通带',C.blue]]);}else caption(`fₛ = ${fs} Hz · fₛ/2 = ${fs/2} Hz`,fs===6?'来自相邻副本的 ±1 Hz 落入中央频带，产生混叠。':'±5 Hz 在中央折叠频带内；理论比例因子为 1/T。',[['原副本 ±5 Hz',C.teal],['其他副本',C.orange]]);observed={fs,fold:Math.abs(5-Math.round(5/fs)*fs)};}
function reconstruction(mode){const g=axes({xmin:-.5,xmax:.5,ymin:-1.45,ymax:1.45,h:mode==='compare'?228:272});series(g,RECON.t,RECON.reference,C.gray,2.5);let c=reco(),k=0;
 if(mode==='basis'){let n=manual?Number($('#basis').value):(cue()===0?0:1);$('#basis').value=String(n);const weighted=cue()>0||manual;const t=RECON.t,v=t.map(t=>sinc(t*12-n)*(weighted?Math.cos(2*Math.PI*5*n/12):1));if(weighted)series(g,t,t.map(t=>sinc(t*12-n)),C.blue,2,[7,4]);series(g,t,v,C.orange,3);let ys=c.tn.map(t=>sinc(t*12-n)*(weighted?Math.cos(2*Math.PI*5*n/12):1));stems(g,c.tn,ys,C.orange);caption(`中心 N = ${n} · t = ${(n/12).toFixed(4)} s`,weighted?`权重 x[${n}] = ${Math.cos(2*Math.PI*5*n/12).toFixed(3)}；蓝色基函数中心为 1，橙色加权中心为 x[N]；其余整数采样位置均为零。`:'未加权 sinc 在中心为 1；其他整数间隔处为 0。',[['已知原信号',C.gray],...(weighted?[['未加权基函数',C.blue]]:[]),['单项贡献',C.orange]]);observed={n,weighted};return;}
 if(mode==='sum'){k=manual?Number($('#terms').value)-1:Math.min(24,Math.floor(progress()*25));$('#terms').value=String(k+1);$('#term-count').textContent=`${k+1} / 25`;series(g,RECON.t,RECON.terms[k],C.blue,1.8);series(g,RECON.t,RECON.partials[k],C.orange,3);const indices=RECON.order.slice(0,k+1);stems(g,indices.map(n=>n/12),indices.map(n=>Math.cos(2*Math.PI*5*n/12)));caption(`已加入 ${k+1} / 25 项 · 本次 N = ${RECON.order[k]}`,'灰色是仿真参考；重建只使用采样时刻与样本值。',[['原信号',C.gray],['本次单项',C.blue],['部分和',C.orange]]);observed={terms:k+1,n:RECON.order[k]};return;}
 if(mode==='length'){const M=[12,36,120][Math.min(2,Math.floor(progress()*3))];c=reco(12,M);}
 let method='sinc';if(mode==='lab'){const [fs,M]=$('#rconfig').value.split('-').map(Number);c=reco(fs,M);method=$('#method').value;}
 if(mode==='compare'){[['hold',C.blue],['linear',C.red],['sinc',C.orange]].forEach(([m,col])=>series(g,RECON.t,c[m],col,2.3));const scan=Math.min(RECON.t.length-1,Math.floor(progress()*(RECON.t.length-1)));ctx.setLineDash([4,4]);line(g.px(RECON.t[scan]),g.y,g.px(RECON.t[scan]),g.y+g.h,C.teal,1.5);ctx.setLineDash([]);[['hold',C.blue],['linear',C.red],['sinc',C.orange]].forEach(([m,col])=>dot(g.px(RECON.t[scan]),g.py(c[m][scan]),col,5));['保持','线性','sinc'].forEach((m,i)=>{label(58+i*270,340,m,18,[C.blue,C.red,C.orange][i]);label(58+i*270,366,`RMSE ${c.rmse[i].toFixed(4)}`,16);label(58+i*270,390,`最大差 ${c.maxerr[i].toFixed(4)}`,16);});caption('同一组 25 个样本 · 三种恢复方法','误差评价区间 [−0.5,0.5] 秒；数值为密集网格结果。',[['参考余弦',C.gray],['保持',C.blue],['线性',C.red],['sinc',C.orange]]);}else{series(g,RECON.t,c[method],C.orange,3);if(c.fs===6)series(g,RECON.t,RECON.alias_reference,C.teal,2,[7,4]);let j=['hold','linear','sinc'].indexOf(method);caption(`${c.fs} Hz · ${c.count} 个样本 · ${method}`,`对 5 Hz：RMSE ${c.rmse[j].toFixed(6)}，最大差 ${c.maxerr[j].toFixed(6)}。`+(c.fs===6&&method==='sinc'?` 对 1 Hz：RMSE ${c.alias_rmse.toFixed(6)}。`:''),[['原 5 Hz',C.gray],['恢复结果',C.orange],...(c.fs===6?[['1 Hz 候选',C.teal]]:[])]);}stems(g,c.tn,c.samples);observed={fs:c.fs,M:c.M,method,count:c.count,rmse:c.rmse,maxerr:c.maxerr,aliasRmse:c.alias_rmse};}
function draw(){const scale=Math.min(devicePixelRatio||1,2);if(cv.width!==900*scale){cv.width=900*scale;cv.height=410*scale;}ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,900,410);let kind=s().kind;
 if(kind==='model')model();if(kind==='derive')triangles();if(kind==='rates')sampling(cue()===0?20:cue()===1?12:6,'cos',cue()>=2);
 if(kind==='alias')sampling(6,'cos',true,true);if(kind==='spectrum')spectral(cue()===0?20:cue()===1?12:6);if(kind==='critical')sampling(10,cue()<2?'sin':'cos',false);
 if(kind==='lowpass')spectral(12,true);if(['basis','sum','compare','length'].includes(kind))reconstruction(kind);
 if(kind==='lab'){const isSample=$('#labmode').value==='sampling';controls(isSample?['labmode','fs','wave']:['labmode','rconfig','method']);isSample?sampling(Number($('#fs').value),$('#wave').value,Number($('#fs').value)===6):reconstruction('lab');}
}
function fmt(t){return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
function update(){const i=cue();if(i!==lastCue){$('#transcript').textContent=s().units[i].text;lastCue=i;}$('#cue-index').textContent=s().audio?`${i+1} / ${s().units.length}`:'自由实验';$('#clock').textContent=s().audio?`${fmt(tm())} / ${fmt(s().duration)}`:'自由实验';$('#seek').value=tm();$('#prev-cue').disabled=!s().audio||i===0;$('#next-cue').disabled=!s().audio||i===s().units.length-1;draw();}
function playing(){const on=!!s().audio&&!a.paused;$('#play').innerHTML=on?'Ⅱ<span>暂停讲解</span>':'▶<span>播放讲解</span>';$('#play').setAttribute('aria-label',on?'暂停讲解':'播放讲解');}
function tick(){update();if(!a.paused)raf=requestAnimationFrame(tick);}
function navigate(n){n=clamp(n,0,SLIDES.length-1);token++;a.pause();cancelAnimationFrame(raf);page=n;lastCue=-1;manual=false;$('#section').textContent=`CHAPTER 02 / ${String(n+1).padStart(2,'0')}`;$('#title').textContent=s().title;$('#lead').textContent=s().lead;$('#concept').textContent=s().concept;$('#formula').innerHTML=s().formula;$('#points').innerHTML=s().points.map(t=>`<p>${t}</p>`).join('');$('#takeaway').textContent=s().takeaway;cv.setAttribute('aria-label',s().title+'。'+s().takeaway);$('#page-number').textContent=`${String(n+1).padStart(2,'0')} / 12`;$('#prev').disabled=n===0;$('#next').disabled=n===SLIDES.length-1;
 document.querySelectorAll('#pages button').forEach((b,i)=>{i===n?b.setAttribute('aria-current','step'):b.removeAttribute('aria-current');});const active=$(`#pages button[data-page="${n}"]`),nav=$('#pages');if(active.offsetLeft<nav.scrollLeft||active.offsetLeft+active.offsetWidth>nav.scrollLeft+nav.clientWidth)nav.scrollLeft=active.offsetLeft-nav.offsetLeft;
 controls(s().kind==='model'?['model','duty']:s().kind==='basis'?['basis']:s().kind==='sum'?['terms']:[]);
 for(const id of ['play','reset','seek','sound','speed'])$('#'+id).disabled=!s().audio;
 if(s().audio){a.src=s().audio;a.load();a.playbackRate=Number($('#speed').value);a.muted=!$('#sound').checked;$('#seek').max=s().duration;}else{a.removeAttribute('src');a.load();$('#seek').value=0;}
 $('#status').textContent=s().audio?'空格播放 / 暂停，左右键翻页；每屏结束后停留，便于讨论。':'先预测，再改变参数；每次只改一个条件。';try{history.replaceState(null,'',`#${n+1}`);}catch(e){}playing();update();}
async function toggle(){if(!s().audio)return;if(!a.paused){a.pause();return;}manual=false;if(tm()>=s().duration-.1)a.currentTime=0;let v=token;try{await a.play();if(v===token)$('#status').textContent='讲解与动画同步播放；改变演示参数会暂停讲解。';}catch(e){if(v===token)$('#status').textContent='音频暂时无法播放，请检查 assets 文件夹；可拖动进度查看图文。';}}
$('#pages').innerHTML=SLIDES.map((x,i)=>`<button data-page="${i}" aria-label="第 ${i+1} 屏 ${x.nav}">${String(i+1).padStart(2,'0')} ${x.nav}</button>`).join('');$('#pages').onclick=e=>{let b=e.target.closest('button');if(b)navigate(Number(b.dataset.page));};
$('#prev').onclick=()=>navigate(page-1);$('#next').onclick=()=>navigate(page+1);$('.brand').onclick=e=>{e.preventDefault();navigate(0);};$('#play').onclick=toggle;
$('#reset').onclick=()=>{manual=false;a.pause();a.currentTime=0;update();};$('#seek').oninput=e=>{manual=false;a.currentTime=Number(e.target.value);update();};$('#sound').onchange=()=>a.muted=!$('#sound').checked;$('#speed').onchange=()=>a.playbackRate=Number($('#speed').value);
function seekCue(delta){if(!s().audio)return;manual=false;a.currentTime=s().units[clamp(cue()+delta,0,s().units.length-1)].start+.02;update();}$('#prev-cue').onclick=()=>seekCue(-1);$('#next-cue').onclick=()=>seekCue(1);
document.querySelectorAll('#controls select,#controls input').forEach(el=>el.addEventListener('input',()=>{a.pause();manual=true;draw();if(s().audio)$('#status').textContent='已暂停，正在手动观察。再次播放时恢复与讲解同步的演示。';}));
a.onplay=()=>{cancelAnimationFrame(raf);playing();tick();};a.onpause=()=>{cancelAnimationFrame(raf);playing();update();};a.onseeked=update;a.onloadedmetadata=()=>{a.playbackRate=Number($('#speed').value);update();};a.onended=()=>{playing();update();$('#status').textContent='本屏讲解结束。可暂停讨论，或进入下一屏。';};a.onerror=()=>{if(s().audio&&a.getAttribute('src'))$('#status').textContent='未能加载音频，请检查 assets 文件夹是否完整。';};
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,button,summary,a')||e.altKey||e.ctrlKey||e.metaKey)return;if(e.code==='Space'){e.preventDefault();toggle();}if(e.code==='ArrowLeft'){e.preventDefault();navigate(page-1);}if(e.code==='ArrowRight'){e.preventDefault();navigate(page+1);}});
$('#full').onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await $('.deck').requestFullscreen();}catch(e){$('#status').textContent='可使用浏览器 F11 全屏。';}};document.addEventListener('fullscreenchange',()=>$('#full').textContent=document.fullscreenElement?'退出全屏':'全屏投影');document.addEventListener('visibilitychange',()=>{if(document.hidden)a.pause();});window.addEventListener('resize',draw);window.addEventListener('hashchange',()=>{let n=Number(location.hash.slice(1))-1;if(Number.isInteger(n)&&n>=0&&n<SLIDES.length&&n!==page)navigate(n);});
window.lessonState=()=>({page,time:tm(),cue:cue(),manual,...observed});const hash=Number(location.hash.slice(1));navigate(hash>=1&&hash<=SLIDES.length?hash-1:0);
})();
